export type LangCode = "en" | "vi" | "ja" | "unknown"

export type TranscriptLine = {
  start: number
  duration: number
  text: string
}

export type CaptionTrack = {
  baseUrl: string
  languageCode: string
  name: string
  kind?: string
}

export type FetchTranscriptResult = {
  lines: TranscriptLine[]
  language: LangCode
  sourceLanguageCode: string
  isAutoGenerated: boolean
}
